#Cet inventaire n'est pas a copier coller, il est créé automatiquement lors de l'exécution des playbooks.
[Serveur]
IP_serveur ansible_user=user

[Clients]
Hostname_client1 ansible_host=IP_client1 ansible_user=root mac=AA:BB:CC:DD:EE:FF carte=netplan-Nom_de_carte1 machine_id=ID_unique_machine1 date=AAAA-MM-JJ

# ...

[UserAnsible]
Hostname_client1 ansible_host=IP_client1 ansible_user=ansible mac=AA:BB:CC:DD:EE:FF carte=netplan-Nom_de_carte1 machine_id=ID_unique_machine1 date=AAAA-MM-JJ

# ...