---
# Partie 1/3 : Création automatique du fichier Inventaire2.ini
#
# Objectif :
# - Créer l'Inventaire2.ini avec une structure Ansible
#   de façon à l'utiliser pour WoL plus tard
#
# Le fichier ne sera pas écrasé s'il existe déjà
# afin de conserver les anciens PCs ajoutés,
# lors de l'ajout de nouveaux PCs.

- name: Initialiser inventaire

# Exécution sur le serveur Ansible
  hosts: localhost

# Exécution directement sur le serveur Ansible
  become: no

  tasks:

# Bloc de création de l'inventaire
    - block:

# Création du fichier inventaire initial
        - name: Créer Inventaire2.ini
          copy:

# Emplacement du fichier final
            dest: /chemin/vers/Inventaire2.ini

# Contenu créé au premier lancement
            content: |
              [Serveur]
              IP_serveur ansible_user=user

              [Clients]

              [UserAnsible]

# Ne remplace pas un inventaire déjà existant
            force: no

# Si la création échoue
      rescue:

        - name: Log erreur création inventaire
          lineinfile:
            path: /chemin/vers/ansibleFails.log
            create: yes

# Format de type :
# 2026-06-22 15:17:32 | PC concerné | Nom de l'erreur
            line: "{{ lookup('pipe','TZ=Europe/Paris date +\"%Y-%m-%d %H:%M:%S\"') }} | localhost | création Inventaire2 failed"

# Partie 2/3 : Récupération des informations réseau
#
# Objectif, récupérer :
# - Nom du PC
# - Adresse IP
# - Adresse MAC
# - Carte réseau utilisée
# - Identifiant unique du système Linux
# - Date d'ajout dans l'inventaire

- name: Récupérer informations réseau

# Exécute les commandes sur tous les PCs du groupe Clients
  hosts: Clients

# Utilisation des droits administrateur
  become: yes

  tasks:

# Bloc principal de récupération
    - block:

# Récupération du nom de la machine
        - name: Récupérer le hostname du PC
          command: hostname

# Sauvegarde du résultat dans une variable
# Utilisation : hostname_pc.stdout
          register: hostname_pc

# Récupération de l'interface réseau active
        - name: Récupérer la carte réseau active
          shell: |
            ip route | grep default | awk '{print $5}'

# Stockage de l'interface
          register: interface_reseau

# Récupération de l'adresse MAC
        - name: Récupérer l'adresse MAC
          shell: |
            ip link show {{ interface_reseau.stdout }} | grep ether | awk '{print $2}'
          register: mac_pc

# Récupération de l'adresse IP
        - name: Récupérer IP du PC
          shell: |
            ip -4 addr show {{ interface_reseau.stdout }} | grep inet | awk '{print $2}' | cut -d/ -f1
          register: ip_pc

# Récupération de l'identifiant unique de la machine Linux
# Sert à identifier le PC de manière unique
        - name: Récupérer Machine ID
          command: cat /etc/machine-id
          register: machine_id

# Date d'ajout dans l'inventaire
        - name: Récupérer date ajout
          command: date "+%Y-%m-%d"
          register: date_ajout

# En cas d'erreur pendant la récupération
      rescue:

        - name: Log erreur récupération réseau
          become: no
          lineinfile:
            path: /chemin/vers/ansibleFails.log
            create: yes
            line: "{{ lookup('pipe','TZ=Europe/Paris date +\"%Y-%m-%d %H:%M:%S\"') }} | {{ inventory_hostname }} | récupération failed"
          delegate_to: localhost

# Partie 3/3 : Ajout automatique dans Inventaire2.ini
#
# Objectif :
# Ajouter le PC dans les deux groupes :
#
# Clients :
# Connexion root temporaire pour préparation
#
# UserAnsible :
# Connexion finale avec l'utilisateur ansible

    - block:

# Ajout du PC dans Clients
        - name: Ajouter PC dans Clients
          become: no
          lineinfile:
            path: /chemin/vers/Inventaire2.ini
            create: yes

# Ajoute sous [Clients]
            insertafter: '^\[Clients\]$'

# Empêche les doublons
            regexp: "^{{ hostname_pc.stdout }} .*ansible_user=root"

# Ligne finale ajoutée
            line: "{{ hostname_pc.stdout }} ansible_host={{ ip_pc.stdout }} ansible_user=root mac={{ mac_pc.stdout }} carte=netplan-{{ interface_reseau.stdout }} machine_id={{ machine_id.stdout }} date={{ date_ajout.stdout }}"
          delegate_to: localhost

# Ajout du PC dans UserAnsible
        - name: Ajouter PC dans UserAnsible
          become: no
          lineinfile:
            path: /chemin/vers/Inventaire2.ini
            create: yes

# Ajoute sous [UserAnsible]
            insertafter: '^\[UserAnsible\]$'

# Empêche les doublons
            regexp: "^{{ hostname_pc.stdout }} .*ansible_user=ansible"

# Ligne finale utilisateur ansible
            line: "{{ hostname_pc.stdout }}_ansible ansible_host={{ ip_pc.stdout }} ansible_user=ansible mac={{ mac_pc.stdout }} carte=netplan-{{ interface_reseau.stdout }} machine_id={{ machine_id.stdout }} date={{ date_ajout.stdout }}"
          delegate_to: localhost

# Si l'ajout échoue
      rescue:

        - name: Log erreur sauvegarde
          become: no
          lineinfile:
            path: /chemin/vers/ansibleFails.log
            create: yes
            line: "{{ lookup('pipe','TZ=Europe/Paris date +\"%Y-%m-%d %H:%M:%S\"') }} | {{ inventory_hostname }} | sauvegarde failed"
          delegate_to: localhost